### ISSUE TITLE
File based webservice backends

### ISSUE THREAD

**Issue by Svarto** [XA21X/traefik-idc-demo#1]
Thanks for much for providing this demo. Just so I understand correctly, the nginx in your example is an example of how to configure a backend - I could switch out that container for any other webservice to place it behind the openresty authentication?

Have you come across how to configure it for a File backend instead of Docker?

**Comment by XA21X** [comment]
Yes, there is nothing special about Docker. I use the file backend myself for a few non-Dockerised services. It should just be a matter of setting [`entryPoints.*.auth.forward.address`](https://docs.traefik.io/configuration/entrypoints/#forward-authentication) or `frontends.*.auth.forward.address`. The latter has been supported since containous/traefik#3559 but the documentation for the file backend doesn't seem to be have been updated. Here's an example:

```
[backends.my_backend.servers.my_server]
  url = "http://blah.internal.example.com:80"

[frontends.my_frontend]
  backend = "my_backend"

  [frontends.my_frontend.auth.forward]
    address = "http://openresty/"

  [frontends.my_frontend.routes.my_route]
    rule = "Host: blah.example.com"
```

Anything I've prefixed with `my_` can be replaced with _any_ valid name.
